"""
Generate version_info.txt for PyInstaller builds.

This script reads version information from src.__version__.py and generates
the version_info.txt file used by PyInstaller to embed version information
into the Windows executable.

Usage:
    python scripts/generate_version_info.py

Output:
    version_info.txt in project root
"""

import sys
from pathlib import Path

# Add project root to path for imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from src.__version__ import __version__, __build__, VERSION_INFO


def generate_version_info():
    """Generate version_info.txt from version constants."""

    # Parse version string
    major, minor, patch, build = VERSION_INFO

    # Generate version info content
    content = f'''# UTF-8
#
# Version resource file for ProjectorControl.exe
# Auto-generated by scripts/generate_version_info.py
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Your Organization'),
            StringStruct('FileDescription', 'Enhanced Projector Control Application'),
            StringStruct('FileVersion', '{major}.{minor}.{patch}.{build}'),
            StringStruct('InternalName', 'ProjectorControl'),
            StringStruct('LegalCopyright', 'Copyright (c) 2026'),
            StringStruct('OriginalFilename', 'ProjectorControl.exe'),
            StringStruct('ProductName', 'Projector Control'),
            StringStruct('ProductVersion', '{major}.{minor}.{patch}.{build}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''

    # Write to version_info.txt
    output_path = project_root / "version_info.txt"
    output_path.write_text(content, encoding='utf-8')

    print(f"OK Generated version_info.txt with version {__version__}.{build}")
    print(f"  Output: {output_path}")

    return True


if __name__ == "__main__":
    try:
        generate_version_info()
        sys.exit(0)
    except Exception as e:
        print(f"ERROR Error generating version_info.txt: {e}", file=sys.stderr)
        sys.exit(1)
